stages:
  - build
  - deploy

back:build:
  stage: build
  image:  maven:3.8.3-openjdk-17
  script:
    - echo "Building app..."
    - cd Back/IntegradorMaven
    - mvn clean install -DskipTests
    - echo "Finished building the app."
  artifacts:
    expire_in: 1 week
    paths:
      - Back/IntegradorMaven/target/java-backend.service.jar

front:build:
  stage: build
  image:  20-alpine3.16
  script:
    - echo "Building app..."
    - cd Front
    - npm install
    - npm run build
    - echo "Finished building the app."
  artifacts:
    expire_in: 1 week
    paths:
      - Front/dist

back:deploy:
  stage: deploy
  image: alpine:3.11
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "Deploying started..."
    - ssh ec2-user@$DEPLOY_SERVER_IP "sudo systemctl stop java-backend.service"
    - scp Back/IntegradorMaven/target/java-backend.service.jar ec2-user@$DEPLOY_SERVER_IP:~/java-backend/
    - ssh ec2-user@$DEPLOY_SERVER_IP "sudo systemctl start java-backend.service"
    - echo "Finished deploying the app."
  only:
    - Develop